import type { Dungeon } from '../types';

export const dungeons: Dungeon[] = [
  {
    id: 'dungeon_1',
    name: 'Cavernas Rasas',
    description: 'Cavernas superficiais habitadas por slimes e goblins fracos.',
    level: 1,
    minTitle: 'novato',
    recommendedTitle: 'novato',
    theme: 'cavern',
    rewardGoldPerTick: 1,
    experiencePerTick: 2,
    rarityWeights: { common: 75, uncommon: 22, rare: 3, epic: 0, legendary: 0 },
    pool: ['slime', 'cavern_bat', 'goblin', 'arcane_shroom', 'goblin_shaman'],
  },
  {
    id: 'dungeon_2',
    name: 'Floresta Sombria',
    description: 'Floresta densa assombrada por criaturas da noite.',
    level: 2,
    minTitle: 'explorador',
    recommendedTitle: 'explorador',
    theme: 'forest',
    rewardGoldPerTick: 3,
    experiencePerTick: 6,
    rarityWeights: { common: 50, uncommon: 38, rare: 10, epic: 2, legendary: 0 },
    pool: ['shadow_wolf', 'forest_spirit', 'treant', 'banshee'],
  },
  {
    id: 'dungeon_3',
    name: 'Masmorra do Dragão',
    description: 'Profundezões onde um dragão ancião guarda tesouros lendários.',
    level: 3,
    minTitle: 'heroi',
    recommendedTitle: 'heroi',
    theme: 'draconic',
    rewardGoldPerTick: 8,
    experiencePerTick: 15,
    rarityWeights: { common: 40, uncommon: 35, rare: 18, epic: 6, legendary: 1 },
    pool: ['orc', 'corrupted_scout', 'red_drake', 'ancient_dragon'],
  },
  {
    id: 'dungeon_4',
    name: 'Picos do Trovão',
    description: 'Montanhas fustigadas por tempestades eternas e criaturas de pedra e raio.',
    level: 4,
    minTitle: 'conquistador',
    recommendedTitle: 'conquistador',
    theme: 'thunder',
    rewardGoldPerTick: 15,
    experiencePerTick: 30,
    rarityWeights: { common: 30, uncommon: 32, rare: 25, epic: 10, legendary: 3 },
    pool: ['thunder_elemental', 'stone_golem', 'thunder_knight', 'storm_fury'],
  },
  {
    id: 'dungeon_5',
    name: 'Abismo do Vazio',
    description: 'Fenda no mundo onde a escuridão primordial ainda se move.',
    level: 5,
    minTitle: 'mitico',
    recommendedTitle: 'mitico',
    theme: 'abyss',
    rewardGoldPerTick: 24,
    experiencePerTick: 50,
    rarityWeights: { common: 20, uncommon: 30, rare: 28, epic: 15, legendary: 7 },
    pool: ['abyss_devourer', 'voracious_specter', 'ancient_horror', 'the_void'],
  },
];

export function getDungeon(id: string): Dungeon | undefined {
  return dungeons.find((d) => d.id === id);
}