import type { ItemDefinition } from '../types';

export const itemDefinitions: Record<string, ItemDefinition> = {
  // ===== Materiais =====
  wood: {
    id: 'wood',
    name: 'Madeira',
    type: 'material',
    rarity: 'common',
    description: 'Tábua de madeira comum, usada em diversas receitas.',
  },
  iron_ore: {
    id: 'iron_ore',
    name: 'Minério de Ferro',
    type: 'material',
    rarity: 'common',
    description: 'Minério bruto que pode ser refinado em equipamentos.',
  },
  cloth: {
    id: 'cloth',
    name: 'Tecido',
    type: 'material',
    rarity: 'common',
    description: 'Tecido simples feito de fibras vegetais.',
  },
  magic_essence: {
    id: 'magic_essence',
    name: 'Essência Mágica',
    type: 'material',
    rarity: 'uncommon',
    description: 'Resquícios de energia arcana pulsante.',
  },
  dragon_scale: {
    id: 'dragon_scale',
    name: 'Escama de Dragão',
    type: 'material',
    rarity: 'rare',
    description: 'Escama rara com propriedades defensivas excepcionais.',
  },
  steel_ingot: {
    id: 'steel_ingot',
    name: 'Lingote de Aço',
    type: 'material',
    rarity: 'uncommon',
    description: 'Lingote refinado de grande resistência, base de forjas avançadas.',
  },
  phoenix_feather: {
    id: 'phoenix_feather',
    name: 'Pluma de Fênix',
    type: 'material',
    rarity: 'rare',
    description: 'Pluma incandescente imbuída de chama vital.',
  },
  void_shard: {
    id: 'void_shard',
    name: 'Fragmento do Vazio',
    type: 'material',
    rarity: 'epic',
    description: 'Estilhaço de pura escuridão, vibrante de poder caótico.',
  },

  // ===== Consumíveis =====
  health_potion: {
    id: 'health_potion',
    name: 'Poção de Vida',
    type: 'consumable',
    rarity: 'uncommon',
    description: 'Restaura 50% da vida máxima instantaneamente.',
    effect: { hpPercent: 50 },
  },
  mana_potion: {
    id: 'mana_potion',
    name: 'Poção de Mana',
    type: 'consumable',
    rarity: 'uncommon',
    description: 'Restaura 50% da mana máxima instantaneamente.',
    effect: { mpPercent: 50 },
  },
  elixir: {
    id: 'elixir',
    name: 'Elixir da Vitalidade',
    type: 'consumable',
    rarity: 'rare',
    description: 'Restaura toda a vida e mana instantaneamente.',
    effect: { hpPercent: 100, mpPercent: 100 },
  },

  // ===== Armas =====
  wooden_sword: {
    id: 'wooden_sword',
    name: 'Espada de Madeira',
    type: 'equipment',
    rarity: 'common',
    description: 'Espada simples de madeira, melhor que nada.',
    slot: 'weapon',
    statBonuses: { physicalDamage: 5 },
  },
  wooden_staff: {
    id: 'wooden_staff',
    name: 'Cajado de Madeira',
    type: 'equipment',
    rarity: 'common',
    description: 'Cajado rústico que canaliza energia mágica.',
    slot: 'weapon',
    statBonuses: { magicalDamage: 5 },
  },
  short_bow: {
    id: 'short_bow',
    name: 'Arco Curto',
    type: 'equipment',
    rarity: 'common',
    description: 'Arco leve de madeira, preciso em curtas distâncias.',
    slot: 'weapon',
    statBonuses: { physicalDamage: 4, precision: 3 },
  },
  iron_sword: {
    id: 'iron_sword',
    name: 'Espada de Ferro',
    type: 'equipment',
    rarity: 'uncommon',
    description: 'Espada forjada em ferro, muito superior à de madeira.',
    slot: 'weapon',
    statBonuses: { physicalDamage: 12 },
  },
  longbow: {
    id: 'longbow',
    name: 'Arco Longo',
    type: 'equipment',
    rarity: 'common',
    description: 'Arco de caça com longo alcance e excelente precisão.',
    slot: 'weapon',
    statBonuses: { physicalDamage: 16, precision: 10, speed: 4 },
  },
  rune_staff: {
    id: 'rune_staff',
    name: 'Cajado Rúnico',
    type: 'equipment',
    rarity: 'common',
    description: 'Cajado gravado com runas que amplificam o fluxo arcano.',
    slot: 'weapon',
    statBonuses: { magicalDamage: 18, maxMp: 15, regenMp: 2 },
  },
  steel_sword: {
    id: 'steel_sword',
    name: 'Lâmina de Aço',
    type: 'equipment',
    rarity: 'common',
    description: 'Lâmina de aço temperado, forte e confiável.',
    slot: 'weapon',
    statBonuses: { physicalDamage: 18, speed: 3 },
  },
  warhammer: {
    id: 'warhammer',
    name: 'Martelo de Guerra',
    type: 'equipment',
    rarity: 'common',
    description: 'Martelo pesado que esmaga armaduras.',
    slot: 'weapon',
    statBonuses: { physicalDamage: 24, maxHp: 10 },
  },
  dragon_blade: {
    id: 'dragon_blade',
    name: 'Lâmina do Dragão',
    type: 'equipment',
    rarity: 'rare',
    description: 'Espada imbuída com o poder flamejante dos dragões.',
    slot: 'weapon',
    statBonuses: { physicalDamage: 25, magicalDamage: 10 },
  },
  arcane_tome: {
    id: 'arcane_tome',
    name: 'Grimório Arcano',
    type: 'equipment',
    rarity: 'common',
    description: 'Grimório que concentra um manancial de energia arcana.',
    slot: 'weapon',
    statBonuses: { magicalDamage: 24, maxMp: 25 },
  },
  shadow_blade: {
    id: 'shadow_blade',
    name: 'Lâmina Sombria',
    type: 'equipment',
    rarity: 'common',
    description: 'Lâmina forjada na escuridão do Vazio, voraz e veloz.',
    slot: 'weapon',
    statBonuses: { physicalDamage: 28, speed: 8 },
  },

  // ===== Armaduras =====
  leather_armor: {
    id: 'leather_armor',
    name: 'Armadura de Couro',
    type: 'equipment',
    rarity: 'common',
    description: 'Armadura leve de couro, protege contra golpes básicos.',
    slot: 'armor',
    statBonuses: { physicalDefense: 5 },
  },
  cloth_robe: {
    id: 'cloth_robe',
    name: 'Túnica de Tecido',
    type: 'equipment',
    rarity: 'common',
    description: 'Túnica simples que oferece proteção mágica básica.',
    slot: 'armor',
    statBonuses: { magicalDefense: 5 },
  },
  iron_armor: {
    id: 'iron_armor',
    name: 'Armadura de Ferro',
    type: 'equipment',
    rarity: 'uncommon',
    description: 'Armadura robusta de ferro, excelente proteção física.',
    slot: 'armor',
    statBonuses: { physicalDefense: 15, maxHp: 20 },
  },
  steel_armor: {
    id: 'steel_armor',
    name: 'Armadura de Aço',
    type: 'equipment',
    rarity: 'common',
    description: 'Placas de aço que oferecem proteção superior.',
    slot: 'armor',
    statBonuses: { physicalDefense: 20, maxHp: 25 },
  },
  rune_robe: {
    id: 'rune_robe',
    name: 'Túnica Rúnica',
    type: 'equipment',
    rarity: 'common',
    description: 'Tecido entrelaçado com fios rúnicos e mana pulsante.',
    slot: 'armor',
    statBonuses: { magicalDefense: 15, maxMp: 25, regenMp: 2 },
  },
  ranger_cloak: {
    id: 'ranger_cloak',
    name: 'Manto do Patrulheiro',
    type: 'equipment',
    rarity: 'common',
    description: 'Manto leve que não impede movimentos rápidos.',
    slot: 'armor',
    statBonuses: { physicalDefense: 12, speed: 6, precision: 4 },
  },
  dragon_scale_armor: {
    id: 'dragon_scale_armor',
    name: 'Armadura de Escama de Dragão',
    type: 'equipment',
    rarity: 'rare',
    description: 'Armadura lendária forjada com escamas de dragão.',
    slot: 'armor',
    statBonuses: { physicalDefense: 30, magicalDefense: 25, maxHp: 50 },
  },
  void_plate: {
    id: 'void_plate',
    name: 'Placa do Vazio',
    type: 'equipment',
    rarity: 'common',
    description: 'Armadura que absorve a escuridão do Abismo.',
    slot: 'armor',
    statBonuses: { physicalDefense: 35, magicalDefense: 30, maxHp: 40 },
  },

  // ===== Acessórios =====
  iron_ring: {
    id: 'iron_ring',
    name: 'Anel de Ferro',
    type: 'equipment',
    rarity: 'common',
    description: 'Anel simples que fortalece o usuário.',
    slot: 'accessory',
    statBonuses: { maxHp: 10 },
  },
  mage_ring: {
    id: 'mage_ring',
    name: 'Anel do Mago',
    type: 'equipment',
    rarity: 'uncommon',
    description: 'Anel imbuído com poder arcano.',
    slot: 'accessory',
    statBonuses: { magicalDamage: 8, maxMp: 20 },
  },
  strength_ring: {
    id: 'strength_ring',
    name: 'Anel da Força',
    type: 'equipment',
    rarity: 'common',
    description: 'Anel que amplia a força física do portador.',
    slot: 'accessory',
    statBonuses: { physicalDamage: 8, maxHp: 15 },
  },
  mage_amulet: {
    id: 'mage_amulet',
    name: 'Amuleto do Mago',
    type: 'equipment',
    rarity: 'common',
    description: 'Cristal arcano que canaliza as energias do usuário.',
    slot: 'accessory',
    statBonuses: { magicalDamage: 10, maxMp: 30 },
  },
  guardian_pendant: {
    id: 'guardian_pendant',
    name: 'Pingente do Guardião',
    type: 'equipment',
    rarity: 'common',
    description: 'Talismã que concede vigor e resiliência.',
    slot: 'accessory',
    statBonuses: { physicalDefense: 8, maxHp: 30, regenHp: 2 },
  },

  // ===== Receitas =====
  recipe_iron_sword: {
    id: 'recipe_iron_sword',
    name: 'Receita: Espada de Ferro',
    type: 'recipe',
    rarity: 'uncommon',
    description: 'Instruções para forjar uma Espada de Ferro.',
    ingredients: [{ itemId: 'iron_ore', quantity: 5 }, { itemId: 'wood', quantity: 2 }],
    resultItemId: 'iron_sword',
  },
  recipe_iron_armor: {
    id: 'recipe_iron_armor',
    name: 'Receita: Armadura de Ferro',
    type: 'recipe',
    rarity: 'uncommon',
    description: 'Instruções para forjar uma Armadura de Ferro.',
    ingredients: [{ itemId: 'iron_ore', quantity: 8 }, { itemId: 'cloth', quantity: 3 }],
    resultItemId: 'iron_armor',
  },
  recipe_mage_ring: {
    id: 'recipe_mage_ring',
    name: 'Receita: Anel do Mago',
    type: 'recipe',
    rarity: 'uncommon',
    description: 'Instruções para criar um Anel do Mago.',
    ingredients: [{ itemId: 'magic_essence', quantity: 3 }, { itemId: 'iron_ore', quantity: 2 }],
    resultItemId: 'mage_ring',
  },
  recipe_dragon_scale_armor: {
    id: 'recipe_dragon_scale_armor',
    name: 'Receita: Armadura de Escama de Dragão',
    type: 'recipe',
    rarity: 'rare',
    description: 'Instruções para forjar a lendária Armadura de Escama de Dragão.',
    ingredients: [
      { itemId: 'dragon_scale', quantity: 5 },
      { itemId: 'iron_armor', quantity: 1 },
      { itemId: 'magic_essence', quantity: 4 },
    ],
    resultItemId: 'dragon_scale_armor',
  },
  recipe_dragon_blade: {
    id: 'recipe_dragon_blade',
    name: 'Receita: Lâmina do Dragão',
    type: 'recipe',
    rarity: 'rare',
    description: 'Instruções para forjar a Lâmina do Dragão.',
    ingredients: [
      { itemId: 'dragon_scale', quantity: 3 },
      { itemId: 'iron_sword', quantity: 1 },
      { itemId: 'magic_essence', quantity: 5 },
    ],
    resultItemId: 'dragon_blade',
  },
  recipe_steel_sword: {
    id: 'recipe_steel_sword',
    name: 'Receita: Lâmina de Aço',
    type: 'recipe',
    rarity: 'uncommon',
    description: 'Instruções para forjar uma Lâmina de Aço.',
    ingredients: [{ itemId: 'steel_ingot', quantity: 5 }, { itemId: 'wood', quantity: 3 }],
    resultItemId: 'steel_sword',
  },
  recipe_steel_armor: {
    id: 'recipe_steel_armor',
    name: 'Receita: Armadura de Aço',
    type: 'recipe',
    rarity: 'uncommon',
    description: 'Instruções para forjar uma Armadura de Aço.',
    ingredients: [{ itemId: 'steel_ingot', quantity: 6 }, { itemId: 'cloth', quantity: 4 }],
    resultItemId: 'steel_armor',
  },
  recipe_longbow: {
    id: 'recipe_longbow',
    name: 'Receita: Arco Longo',
    type: 'recipe',
    rarity: 'uncommon',
    description: 'Instruções para confeccionar um Arco Longo.',
    ingredients: [{ itemId: 'wood', quantity: 4 }, { itemId: 'cloth', quantity: 2 }, { itemId: 'steel_ingot', quantity: 1 }],
    resultItemId: 'longbow',
  },
  recipe_rune_staff: {
    id: 'recipe_rune_staff',
    name: 'Receita: Cajado Rúnico',
    type: 'recipe',
    rarity: 'rare',
    description: 'Instruções para gravar um Cajado Rúnico.',
    ingredients: [{ itemId: 'steel_ingot', quantity: 4 }, { itemId: 'magic_essence', quantity: 3 }],
    resultItemId: 'rune_staff',
  },
  recipe_rune_robe: {
    id: 'recipe_rune_robe',
    name: 'Receita: Túnica Rúnica',
    type: 'recipe',
    rarity: 'rare',
    description: 'Instruções para tecer uma Túnica Rúnica.',
    ingredients: [
      { itemId: 'magic_essence', quantity: 4 },
      { itemId: 'cloth', quantity: 3 },
      { itemId: 'steel_ingot', quantity: 2 },
    ],
    resultItemId: 'rune_robe',
  },
  recipe_health_potion: {
    id: 'recipe_health_potion',
    name: 'Receita: Poção de Vida',
    type: 'recipe',
    rarity: 'uncommon',
    description: 'Instruções para alquimia de uma Poção de Vida.',
    ingredients: [{ itemId: 'magic_essence', quantity: 2 }, { itemId: 'cloth', quantity: 2 }],
    resultItemId: 'health_potion',
  },
  recipe_mana_potion: {
    id: 'recipe_mana_potion',
    name: 'Receita: Poção de Mana',
    type: 'recipe',
    rarity: 'uncommon',
    description: 'Instruções para alquimia de uma Poção de Mana.',
    ingredients: [{ itemId: 'magic_essence', quantity: 3 }, { itemId: 'wood', quantity: 2 }],
    resultItemId: 'mana_potion',
  },
  recipe_elixir: {
    id: 'recipe_elixir',
    name: 'Receita: Elixir da Vitalidade',
    type: 'recipe',
    rarity: 'rare',
    description: 'Instruções para destilar o sagrado Elixir da Vitalidade.',
    ingredients: [{ itemId: 'phoenix_feather', quantity: 3 }, { itemId: 'magic_essence', quantity: 5 }],
    resultItemId: 'elixir',
  },
  recipe_shadow_blade: {
    id: 'recipe_shadow_blade',
    name: 'Receita: Lâmina Sombria',
    type: 'recipe',
    rarity: 'epic',
    description: 'Instruções para forjar a Lâmina Sombria no calor do Vazio.',
    ingredients: [
      { itemId: 'void_shard', quantity: 3 },
      { itemId: 'iron_sword', quantity: 1 },
      { itemId: 'magic_essence', quantity: 4 },
    ],
    resultItemId: 'shadow_blade',
  },
  recipe_void_plate: {
    id: 'recipe_void_plate',
    name: 'Receita: Placa do Vazio',
    type: 'recipe',
    rarity: 'epic',
    description: 'Instruções para temperar a Placa do Vazio no Abismo.',
    ingredients: [
      { itemId: 'void_shard', quantity: 4 },
      { itemId: 'steel_armor', quantity: 1 },
      { itemId: 'magic_essence', quantity: 5 },
    ],
    resultItemId: 'void_plate',
  },
  recipe_arcane_tome: {
    id: 'recipe_arcane_tome',
    name: 'Receita: Grimório Arcano',
    type: 'recipe',
    rarity: 'legendary',
    description: 'Instruções para encadernar o lendário Grimório Arcano.',
    ingredients: [
      { itemId: 'phoenix_feather', quantity: 4 },
      { itemId: 'void_shard', quantity: 3 },
      { itemId: 'magic_essence', quantity: 6 },
    ],
    resultItemId: 'arcane_tome',
  },
};

export function getItemDefinition(id: string): ItemDefinition | undefined {
  return itemDefinitions[id];
}

export function getItemsByType(type: ItemDefinition['type']): ItemDefinition[] {
  return Object.values(itemDefinitions).filter((item) => item.type === type);
}

export function getItemsByRarity(rarity: ItemDefinition['rarity']): ItemDefinition[] {
  return Object.values(itemDefinitions).filter((item) => item.rarity === rarity);
}

export function getEquipmentsBySlot(slot: ItemDefinition['slot']): ItemDefinition[] {
  return Object.values(itemDefinitions).filter(
    (item) => item.type === 'equipment' && item.slot === slot,
  );
}