import type { Mob, LootTableEntry } from '../types';
import { getDungeon } from '../dungeons/dungeonDefinitions';

function loot(entries: [itemId: string, chance: number][]): LootTableEntry[] {
  return entries.map(([itemId, chance]) => ({ itemId, chance }));
}

export const mobDefinitions: Record<string, Mob> = {
  // ===== Cavernas Rasas (dungeon_1) =====
  slime: {
    id: 'slime',
    name: 'Slime da Caverna',
    icon: '🟢',
    kind: 'trash',
    dungeonId: 'dungeon_1',
    maxHp: 40,
    damage: 12,
    defense: 0,
    xpReward: 5,
    goldReward: 1,
    lootTable: loot([
      ['wood', 0.25],
      ['cloth', 0.15],
      ['iron_ore', 0.1],
      ['health_potion', 0.03],
    ]),
  },
  cavern_bat: {
    id: 'cavern_bat',
    name: 'Morcego da Caverna',
    icon: '🦇',
    kind: 'trash',
    dungeonId: 'dungeon_1',
    maxHp: 35,
    damage: 14,
    defense: 0,
    xpReward: 6,
    goldReward: 1,
    lootTable: loot([
      ['cloth', 0.2],
      ['iron_ore', 0.08],
      ['iron_ring', 0.02],
      ['health_potion', 0.05],
    ]),
  },
  goblin: {
    id: 'goblin',
    name: 'Goblin Pilhador',
    icon: '👺',
    kind: 'trash',
    dungeonId: 'dungeon_1',
    maxHp: 55,
    damage: 16,
    defense: 2,
    xpReward: 7,
    goldReward: 2,
    lootTable: loot([
      ['wood', 0.15],
      ['iron_ore', 0.2],
      ['wooden_sword', 0.03],
      ['short_bow', 0.02],
      ['health_potion', 0.04],
    ]),
  },

  // ===== Floresta Sombria (dungeon_2) =====
  shadow_wolf: {
    id: 'shadow_wolf',
    name: 'Lobo Sombrio',
    icon: '🐺',
    kind: 'trash',
    dungeonId: 'dungeon_2',
    maxHp: 120,
    damage: 45,
    defense: 3,
    xpReward: 18,
    goldReward: 4,
    lootTable: loot([
      ['iron_ore', 0.25],
      ['cloth', 0.2],
      ['longbow', 0.02],
      ['recipe_health_potion', 0.03],
    ]),
  },
  forest_spirit: {
    id: 'forest_spirit',
    name: 'Espírito da Floresta',
    icon: '🌿',
    kind: 'trash',
    dungeonId: 'dungeon_2',
    maxHp: 90,
    damage: 55,
    defense: 5,
    xpReward: 22,
    goldReward: 6,
    lootTable: loot([
      ['magic_essence', 0.15],
      ['wood', 0.2],
      ['cloth_robe', 0.03],
      ['recipe_mana_potion', 0.03],
    ]),
  },
  treant: {
    id: 'treant',
    name: 'Treant Antigo',
    icon: '🌳',
    kind: 'trash',
    dungeonId: 'dungeon_2',
    maxHp: 160,
    damage: 38,
    defense: 8,
    xpReward: 20,
    goldReward: 5,
    lootTable: loot([
      ['wood', 0.3],
      ['iron_ore', 0.15],
      ['iron_armor', 0.03],
      ['recipe_iron_armor', 0.03],
    ]),
  },
  banshee: {
    id: 'banshee',
    name: 'Banshee',
    icon: '👻',
    kind: 'elite',
    dungeonId: 'dungeon_2',
    maxHp: 140,
    damage: 65,
    defense: 2,
    xpReward: 40,
    goldReward: 12,
    lootTable: loot([
      ['magic_essence', 0.2],
      ['mage_ring', 0.04],
      ['recipe_mage_ring', 0.03],
    ]),
  },

  // ===== Masmorra do Dragão (dungeon_3) =====
  orc: {
    id: 'orc',
    name: 'Orc Guerreiro',
    icon: '👹',
    kind: 'trash',
    dungeonId: 'dungeon_3',
    maxHp: 220,
    damage: 90,
    defense: 10,
    xpReward: 45,
    goldReward: 10,
    lootTable: loot([
      ['iron_ore', 0.25],
      ['steel_ingot', 0.2],
      ['iron_sword', 0.04],
      ['recipe_steel_sword', 0.03],
    ]),
  },
  corrupted_scout: {
    id: 'corrupted_scout',
    name: 'Escudeiro Corrompido',
    icon: '🛡️',
    kind: 'trash',
    dungeonId: 'dungeon_3',
    maxHp: 250,
    damage: 95,
    defense: 15,
    xpReward: 50,
    goldReward: 12,
    lootTable: loot([
      ['steel_ingot', 0.25],
      ['cloth', 0.15],
      ['iron_armor', 0.04],
      ['recipe_steel_armor', 0.03],
    ]),
  },
  red_drake: {
    id: 'red_drake',
    name: 'Drake Vermelho',
    icon: '🐉',
    kind: 'trash',
    dungeonId: 'dungeon_3',
    maxHp: 300,
    damage: 80,
    defense: 12,
    xpReward: 60,
    goldReward: 15,
    lootTable: loot([
      ['steel_ingot', 0.2],
      ['magic_essence', 0.15],
      ['dragon_scale', 0.1],
      ['mage_ring', 0.04],
      ['recipe_longbow', 0.03],
    ]),
  },
  ancient_dragon: {
    id: 'ancient_dragon',
    name: 'Dragão Ancião',
    icon: '🐲',
    kind: 'boss',
    dungeonId: 'dungeon_3',
    maxHp: 500,
    damage: 120,
    defense: 20,
    xpReward: 150,
    goldReward: 40,
    lootTable: loot([
      ['dragon_scale', 0.15],
      ['dragon_blade', 0.02],
      ['dragon_scale_armor', 0.02],
      ['recipe_dragon_blade', 0.02],
      ['recipe_dragon_scale_armor', 0.02],
      ['recipe_rune_robe', 0.03],
    ]),
  },

  // ===== Picos do Trovão (dungeon_4) =====
  thunder_elemental: {
    id: 'thunder_elemental',
    name: 'Elemental Relâmpago',
    icon: '⚡',
    kind: 'trash',
    dungeonId: 'dungeon_4',
    maxHp: 450,
    damage: 130,
    defense: 15,
    xpReward: 90,
    goldReward: 22,
    lootTable: loot([
      ['steel_ingot', 0.25],
      ['magic_essence', 0.2],
      ['phoenix_feather', 0.08],
      ['rune_staff', 0.03],
      ['recipe_rune_robe', 0.03],
    ]),
  },
  stone_golem: {
    id: 'stone_golem',
    name: 'Golém de Pedra',
    icon: '🗿',
    kind: 'trash',
    dungeonId: 'dungeon_4',
    maxHp: 600,
    damage: 110,
    defense: 25,
    xpReward: 80,
    goldReward: 20,
    lootTable: loot([
      ['steel_ingot', 0.3],
      ['iron_ore', 0.15],
      ['steel_armor', 0.04],
      ['recipe_rune_staff', 0.03],
    ]),
  },
  thunder_knight: {
    id: 'thunder_knight',
    name: 'Cavaleiro do Trovão',
    icon: '⚔️',
    kind: 'trash',
    dungeonId: 'dungeon_4',
    maxHp: 500,
    damage: 150,
    defense: 20,
    xpReward: 110,
    goldReward: 28,
    lootTable: loot([
      ['steel_ingot', 0.2],
      ['phoenix_feather', 0.1],
      ['steel_sword', 0.04],
      ['longbow', 0.03],
    ]),
  },
  storm_fury: {
    id: 'storm_fury',
    name: 'Fúria da Tempestade',
    icon: '🌩️',
    kind: 'boss',
    dungeonId: 'dungeon_4',
    maxHp: 900,
    damage: 180,
    defense: 25,
    xpReward: 250,
    goldReward: 70,
    lootTable: loot([
      ['phoenix_feather', 0.15],
      ['void_shard', 0.05],
      ['dragon_blade', 0.03],
      ['steel_sword', 0.05],
      ['recipe_elixir', 0.03],
    ]),
  },

  // ===== Abismo do Vazio (dungeon_5) =====
  abyss_devourer: {
    id: 'abyss_devourer',
    name: 'Devorador do Abismo',
    icon: '🕳️',
    kind: 'trash',
    dungeonId: 'dungeon_5',
    maxHp: 1100,
    damage: 190,
    defense: 25,
    xpReward: 160,
    goldReward: 40,
    lootTable: loot([
      ['void_shard', 0.15],
      ['phoenix_feather', 0.1],
      ['shadow_blade', 0.03],
      ['recipe_shadow_blade', 0.03],
    ]),
  },
  voracious_specter: {
    id: 'voracious_specter',
    name: 'Espectro Voraz',
    icon: '💀',
    kind: 'trash',
    dungeonId: 'dungeon_5',
    maxHp: 950,
    damage: 210,
    defense: 20,
    xpReward: 180,
    goldReward: 45,
    lootTable: loot([
      ['void_shard', 0.12],
      ['magic_essence', 0.15],
      ['arcane_tome', 0.02],
      ['recipe_arcane_tome', 0.02],
    ]),
  },
  ancient_horror: {
    id: 'ancient_horror',
    name: 'Horror Ancião',
    icon: '😈',
    kind: 'trash',
    dungeonId: 'dungeon_5',
    maxHp: 1300,
    damage: 175,
    defense: 30,
    xpReward: 200,
    goldReward: 50,
    lootTable: loot([
      ['void_shard', 0.18],
      ['phoenix_feather', 0.08],
      ['void_plate', 0.02],
      ['recipe_void_plate', 0.02],
    ]),
  },
  the_void: {
    id: 'the_void',
    name: 'O Vazio',
    icon: '🌌',
    kind: 'boss',
    dungeonId: 'dungeon_5',
    maxHp: 2400,
    damage: 260,
    defense: 35,
    xpReward: 600,
    goldReward: 150,
    lootTable: loot([
      ['void_shard', 0.2],
      ['dragon_blade', 0.03],
      ['dragon_scale_armor', 0.03],
      ['shadow_blade', 0.03],
      ['arcane_tome', 0.03],
      ['void_plate', 0.03],
      ['recipe_arcane_tome', 0.03],
    ]),
  },
};

export function getMob(id: string): Mob | undefined {
  return mobDefinitions[id];
}

export function getMobsByDungeon(dungeonId: string): Mob[] {
  return Object.values(mobDefinitions).filter((mob) => mob.dungeonId === dungeonId);
}

export function getNextMobId(currentMobId: string, dungeonId: string): string | null {
  const dungeon = getDungeon(dungeonId);
  if (!dungeon || dungeon.pool.length === 0) return null;
  const index = dungeon.pool.indexOf(currentMobId);
  // ponytail: cycles the pool in order; weighted/random selection if variety feels samey
  return dungeon.pool[(index + 1) % dungeon.pool.length] ?? dungeon.pool[0];
}